# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fpm2025
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: first-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: first-interaction

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
