# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fpm2025
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: kunzler-solution
service: kunzler-solution

provider:
  name: aws
  runtime: nodejs22.x
  lambdaHashingVersion: '20201221'
  region: us-east-1
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:Scan
              Resource:
                - <arn:here>
                
functions:
  hello:
    handler: src/hello_cloud_world.handler
    events:
      - http:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handler
    events:
      - http:
          path: /item
          method: post
  fetchItems:
    handler: src/fetchItems.handler
    events:
      - http:
          path: /items
          method: get
  fetchItem:
    handler: src/fetchItem.handler
    events:
      - http:
          path: /items/{id}
          method: get
  updateItem:
    handler: src/updateItem.handler
    events:
      - http:
          path: /items/{id}
          method: put
  deleteItem:
    handler: src/deleteItem.handler
    events:
      - http:
          path: /items/{id}
          method: delete

resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: kunzler-dio-db
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
